CREATE TABLE IF NOT EXISTS receipts (
    event_id UUID PRIMARY KEY,
    seller_id VARCHAR(64) NOT NULL,
    message VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP(9) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_state (
    event_id UUID PRIMARY KEY REFERENCES receipts(event_id),
    status VARCHAR(16) NOT NULL CONSTRAINT delivery_status_values
        CHECK (status IN ('DELIVERING', 'RETRYING', 'DELIVERED', 'FAILED', 'INTERRUPTED'))
);

CREATE TABLE IF NOT EXISTS delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL REFERENCES receipts(event_id),
    started_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP(9) WITH TIME ZONE,
    http_status INTEGER,
    outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('PENDING', 'SUCCEEDED', 'HTTP_ERROR', 'NETWORK_ERROR')),
    detail CHARACTER LARGE OBJECT
);

CREATE INDEX IF NOT EXISTS delivery_attempts_event_id_idx ON delivery_attempts(event_id, id);
